apiVersion: v1
kind: Service
metadata:
  name: revuecinema
  namespace: default
  labels:
      tier: backend
      type: api
      name: revuecinema
spec:
  type: LoadBalancer
  selector:
    tier: backend
    type: api
    name: revuecinema
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: revuecinema
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tier: backend
        type: api
        name: revuecinema
    spec:
      containers:
      - image: gcr.io/halogen-proxy-749/revuecinema:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: revuecinema
        ports:
        - containerPort: 8000
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
